### ISSUE TITLE
assertion failed using g_main_context_query

### ISSUE THREAD

**Issue by daurnimator** [pavouk/lgi#112]
In my quest to integrate lgi with a different event library, I tried using a `MainContext`. 
I can't seem to get `g_main_context_query` to not fail:

```lua
lgi=require"lgi"
GLib = lgi.GLib
c = GLib.MainContext()
assert(c:acquire())
c:query(1000)
```
```
**
Lgi:ERROR:marshal.c:1151:lgi_marshal_2c_caller_alloc: assertion failed: (size > 0)
Aborted (core dumped)
```

**Comment by pavouk** [comment]
I'm sorry, GLib.MainContext.query is so demanding/hostile to dynamic introspection that I don't have any intention to support it.  The problem is that its signature contains caller-allocated dyanmically-sized output parameters.  I'm not even sure how should it be mapped to Lua function signature, and implementing it would be nightmare in already over-complex array marshalling code.

If this functionality is really needed, GLib should come with some introspection-friendly API replacement.
