### ISSUE TITLE
Crash when using Gtk.Application:add_window

### ISSUE THREAD

**Issue by fstirlitz** [pavouk/lgi#117]
Running the following:
```lua
require("lgi").Gtk.Application():add_window(require("lgi").Gtk.Window())
```
crashes the interpreter. It shouldn't.

**Comment by psychon** [comment]
Doesn't crash anything here with an up-to-date Debian testing (neither with debian's version of LGI nor with a current git checkout). What am I doing different?
```
$ lua -e 'require("lgi").Gtk.Application():add_window(require("lgi").Gtk.Window())' 

** (lua:8914): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(lua:8914): Gtk-CRITICAL **: New application windows must be added after the GApplication::startup signal has been emitted.
```

**Comment by pavouk** [comment]
I'm able to reproduce crash with fedora22. This is Gio issue, GApplication must probably be created with application_id property set, otherwise it creates not-fully-initialized object and any sensible usage of it crashes inside libgio (not lgi) code.  There is nothing lgi can do with this, so closing.
