### ISSUE TITLE
Pango.lua:176: bad argument #1 to 'fromarray' (lgi.record expected, got table)

### ISSUE THREAD

**Issue by gares** [pavouk/lgi#123]
This is in the test suite and with libpango1.0-dev 1.38.1-1 on Debian.
See also:  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802090

Best,

**Comment by psychon** [comment]
I looked briefly into this and found two things:

- Previously undocumented/unannotated members of `PangoGlyphString` are now annotated: https://git.gnome.org/browse/pango/commit/?id=5b3103d6718af6263a8aa4610e7ac56221399215
- The following patch makes things work for me ("work" = "the test suite does not complain")

```diff
diff --git a/lgi/override/Pango.lua b/lgi/override/Pango.lua
index a900115..4a562d8 100644
--- a/lgi/override/Pango.lua
+++ b/lgi/override/Pango.lua
@@ -171,6 +171,10 @@ end
 Pango.GlyphString._attribute = { glyphs = {} }
 function Pango.GlyphString._attribute.glyphs:get()
    local array = core.record.field(self, Pango.GlyphString._field.glyphs)
+   if type(array) == "table" then
+      -- Always the case since 5b3103d6718af6263a in Pango
+      return array
+   end
    local glyphs = {}
    for i = 0, self.num_glyphs - 1 do
       glyphs[i + 1] = core.record.fromarray(array, i)
```

**Comment by pavouk** [comment]
Funny; your fix came in the meantime while mine was already sitting for a few tens of minutes waiting to be committed :-)

I chose slightly different way to fix the issue.  I'm a bit surprised that your fix kind of worked, because it was dependent on underlying lgi/gi feature which was not implemented yet (array with size as separate fields in the struct).

**Comment by gares** [comment]
I've uploaded the package containing the fix (885af4) to Debian and it worked on all architectures.
Thanks!
