### ISSUE TITLE
GooCanvas is unusable (or: missing documentation)

### ISSUE THREAD

**Issue by fstirlitz** [pavouk/lgi#146]
I wanted to write a small program with a `GooCanvas` in it, but I couldn't find any way to create canvas items.

The closest I got is this:
```lua
local Goo = require('lgi').GooCanvas
local canv = Goo.Canvas()
local item = Goo.CanvasEllipse { parent = canv:get_root_item(); }
```
which gives me the following error message:
```
lua: /usr/share/lua/5.3/lgi/class.lua:157: GooCanvas.CanvasItemSimple: field `parent' is not writable
stack traceback:
	[C]: in field 'field'
	/usr/share/lua/5.3/lgi/class.lua:157: in function </usr/share/lua/5.3/lgi/class.lua:156>
	(...tail calls...)
	[C]: in metamethod '__newindex'
	/usr/share/lua/5.3/lgi/override/GObject-Object.lua:126: in function </usr/share/lua/5.3/lgi/override/GObject-Object.lua:52>
	(...)
```
According to GooCanvas documentation, this is false: `GooCanvasEllipse` implements the `GooCanvasItem` interface, in which specifies the `parent` property as read-write.

**Comment by psychon** [comment]
I don't really know if it helps you, but at least the following kind-of-works for me (kind-of: I have no clue what GooCanvas even is)
```lua
local Goo = require('lgi').GooCanvas
local canv = Goo.Canvas()
local item = Goo.CanvasEllipse()
item:set_parent(canv.root_item)
```
No idea why your code does not work (and no idea why calling `Goo.CanvasEllipse.new` does not work).

**Comment by psychon** [comment]
I took a look at `/usr/share/gir-1.0/GooCanvas-2.0.gir` and I think I know what is going on. `GooCanvasEllipse` implements `GooCanvasItem` which has
```xml
<property name="parent" writable="1" transfer-ownership="none">
   <type name="CanvasItem"/>
</property>
```
This is what you want to access. (Reference: https://developer.gnome.org/goocanvas/stable/GooCanvasItem.html#GooCanvasItem.properties)

However, `GooCanvasEllipse` also inherits from `GooCanvasItemSimple` which has
```xml
<field name="parent">
   <doc xml:space="preserve">the parent item.</doc>
   <type name="CanvasItem" c:type="GooCanvasItem*"/>
</field>
```
This field is not writable. (Reference: https://developer.gnome.org/goocanvas/stable/GooCanvasItemSimple.html#GooCanvasItemSimple-struct)

So in essence, we have a name clash here.

@pavouk Is there any way to get access to the property instead of the field? Could/should lgi preserve properties over fields in cases like this?

**Comment by fstirlitz** [comment]
I translated the example from https://developer.gnome.org/goocanvas/stable/goocanvas-simple-canvas.html into Lua:

```lua
local Gtk = require('lgi').Gtk
local Goo = require('lgi').GooCanvas

local window = Gtk.Window()
window:set_default_size(640, 600)
window:show()
window.on_delete_event = function ()
	Gtk.main_quit()
end

local scrolled_win = Gtk.ScrolledWindow()
scrolled_win:set_shadow_type(Gtk.ShadowType.IN)
scrolled_win:show()
window:add(scrolled_win)

local canvas = Goo.Canvas()
canvas:set_size_request(600, 450)
canvas:set_bounds(0, 0, 1000, 1000)
canvas:show()
scrolled_win:add(canvas)

local root = canvas:get_root_item()

local rect_item = Goo.CanvasRect {
	-- parent = root;
	x = 100; y = 100;
	width = 400;
	height = 400;
	--
	line_width = 10;
	stroke_color = 'yellow';
	fill_color = 'red';
	radius_x = 20;
	radius_y = 10;
}
rect_item:set_parent(root)

local text_item = Goo.CanvasText {
	-- parent = root;
	x = 300; y = 300;
	text = "Hello World";
	width = -1;
	anchor = Goo.CanvasAnchorType.CENTER;
	--
	font = 'Sans 24';
}
text_item:set_parent(root)
text_item:rotate(45, 300, 300)

rect_item.on_button_press_event = function ()
	print("rect item received button press event")
end

Gtk.main()
```

`:set_parent()` doesn't generate an error, but the node doesn't show up in the widget either (lgi bug? GooCanvas bug? not sure). The hack in your second comment works.

**Comment by psychon** [comment]
Hm, `:set_parent()` is kind-of documented not to work here. Whoops.
https://developer.gnome.org/goocanvas/stable/GooCanvasItem.html#goo-canvas-item-set-parent

**Comment by pavouk** [comment]
> @pavouk Is there any way to get access to the property instead of the field? Could/should lgi prefer properties over fields in cases like this?

In general, property access already has higher priority than field access.  I think that the problem here is that while field 'parent' is defined directly in the referenced class, property 'parent' is defined only in inherited interface.  lgi performs lookup in all categories of the class first, and only if not found there it proceeds to parent class chain and after that into implemented interfaces.

The solution here would probably be to disable or rename 'parent' field, something like this (caveat, written into browser and completely untested):

```lua
GooCanvas.CanvasEllipse._field.field_parent = GooCanvas.CanvasEllipse._field.parent
GooCanvas.CanvasEllipse._field.parent = nil
-- Repeat for all canvas item classes...
```

If this will work, we should create new GooCanvas override which is doing this.  I'll do it after I fix DBus issues, unless anyone beats me to it :-)

**Comment by pavouk** [comment]
Hopefully fixed in pavouk/issue-146 branch. Since travis liked the commit, I'm merging it.

**Comment by fstirlitz** [comment]
I'm not terribly pleased with this fix (what if GooCanvas defines yet more shapes in a future version?) but I don't really have an idea how to do this better. For the time being, I'm fine with this.

(Also, it was me who ported the sample... not that I care so much, but still.)

**Comment by pavouk** [comment]
I'm not pleased either. If you find better solution, I'll gladly merge it, and I promise that I will attribute your contribution properly (apologies for doing it wrong this time).
