### ISSUE TITLE
Where is code for indexing ListStore and TreeStore?

### ISSUE THREAD

**Issue by v1993** [pavouk/lgi#158]
I want to write patch for enable indexing ListStore and TreeStore with numbers([0,1,2,...]) or strings(["0:2"]). But I can't found code that provide same functionality for TreeIter. Is it C or Lua part, and where is it?

**Comment by psychon** [comment]
Do you mean `Gtk.ListStore` and `Gtk.TreeStore`?
When compiling Gtk, the code is parsed and a gobject-introspection typelib file is generated. This file describes the available functions, their arguments and things like "this argument may be a NULL pointer" or "the return value from this function must be freed by the caller". At runtime, LGI reads this typelib file and uses its information to provide access to the "real" functions.

I haven't actually checked, but I guess that there is no code in LGI specifically for ListStore and TreeStore. I cannot give you any hints on how to implement what you are looking for, because I do not know the LGI and GObject-Introspection sides of this well enough, and because I have zero clue about ListStore and TreeStore.

**Comment by pavouk** [comment]
Actually, here is quite a bit of override code in lgi for Gtk, `TreeModel` customizations are here: https://github.com/pavouk/lgi/blob/master/lgi/override/Gtk.lua#L292
Documentation for overrides is here:
https://github.com/pavouk/lgi/blob/master/docs/gtk.md#treeview-and-related-classes

Patches welcome!

**Comment by v1993** [comment]
Thank you!

**Comment by v1993** [comment]
Emm... Is it for Gtk.ListStore and Gtk.TreeStore too?

**Comment by psychon** [comment]
Sorry for my wrong hint.

> Emm... Is it for Gtk.ListStore and Gtk.TreeStore too?

The code that pavouk linked to seems to be about Gtk.TreeModel. [Later](https://github.com/pavouk/lgi/blob/master/lgi/override/Gtk.lua#L354-L384) there is some code specific to Gtk.ListStore and [the following lines](https://github.com/pavouk/lgi/blob/master/lgi/override/Gtk.lua#L386-L409) look to me like they do basically the same thing that was just done to Gtk.ListStore also to Gtk.TreeStore.

So, yes, I would say it is for those two, too.

**Comment by v1993** [comment]
Ok, I uderstood this. Thank you.
