### ISSUE TITLE
Gdk.cairo_surface_create_from_pixbuf segfaults

### ISSUE THREAD

**Issue by otommod** [pavouk/lgi#188]
I'm trying to get an image from a URL directly into a `cairo.Surface`.  I'm doing
```lua
lgi = require("lgi")
fp = lgi.Gio.File.new_for_uri("http://via.placeholder.com/350x150")
pb = lgi.GdkPixbuf.Pixbuf.new_from_stream(fp:read())
surface = lgi.Gdk.cairo_surface_create_from_pixbuf(pb, 0)
```

The last call segfaults with output
```
(process:4742): Gdk-CRITICAL **: gdk_display_get_default_screen: assertion 'GDK_IS_DISPLAY (display)' failed

(process:4742): Gdk-CRITICAL **: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
```

However, the following works
```lua
surface = lgi.cairo.ImageSurface(lgi.cairo.Format.RGB24, pb.width, pb.height)
cr = lgi.cairo.Context(surface)
cr:set_source_pixbuf(pb, 0, 0)
cr:paint()
```

All this from ArchLinux with lua 5.3 and (according to pacman) lgi 0.9.2

Also, if there is any other way to do the above do tell!  GNOME docs aren't that good when it comes to discoverability.

**Comment by psychon** [comment]
You have to call `gdk_init` (aka `require("lgi").Gdk.init`) before you can use Gdk (even though I cannot find this example explicitly spelled out in the Gdk docs somewhere).

In your code, what happens is that you pass in `nil` for the last argument of `cairo_surface_create_from_pixbuf`, so Gdk wants to use the screen's root windiow instead. However, it ends up using a NULL pointer instead, because the windowing system was not initialized. If you think that this is a bug, then please report this to Gdk's bugtracker.

If you find another way to do the above, please tell me. I'm looking for one myself. ;-)

**Comment by otommod** [comment]
> You have to call gdk_init (aka require("lgi").Gdk.init) before you can use Gdk (even though I cannot find this example explicitly spelled out in the Gdk docs somewhere).

Oh.  You're right, thank you for clearing this up.  It was obvious that it had something to do with the `for_window` argument but I didn't know what.

However, if I'm running the above from [awesome](http://awesomewm.org), shouldn't `Gdk` be already initialized?

**Comment by psychon** [comment]
Awesome doesn't use Gdk and Gtk. This problem is exactly why the following pull request is adding an own version of `cairo_surface_create_for_pixbuf` to awesome's API: https://github.com/awesomeWM/awesome/pull/2160
(That's also why I recognized the error immediately, I already spent too much time figuring it out. ;-) )
