### ISSUE TITLE
add_color_stop_rgba missing on s390x

### ISSUE THREAD

**Issue by thmo** [pavouk/lgi#212]
On Fedora Rawhide on s390x, I have this strange problem:
```
# lua cairo.lua 
/usr/bin/lua: cairo.lua:177: cairo.SolidPattern: no `add_color_stop_rgba'
stack traceback:
	[C]: in function 'error'
	/usr/share/lua/5.3/lgi/component.lua:160: in function </usr/share/lua/5.3/lgi/component.lua:156>
	[C]: in metamethod '__index'
	cairo.lua:177: in local 'sample'
	cairo.lua:267: in main chunk
	[C]: in ?
```

Unfortunately, I don't see this problem on other architectures. Any hint on how to debug this?

Packages installed:

lua-5.3.5-3.fc30.s390x
lua-lgi-0.9.2-2.fc30.s390x
cairo-1.16.0-3.fc30.s390x
cairo-devel-1.16.0-3.fc30.s390x
cairo-gobject-1.16.0-3.fc30.s390x
cairo-gobject-devel-1.16.0-3.fc30.s390x
gobject-introspection-1.59.4-1.fc30.s390x
gobject-introspection-devel-1.59.4-1.fc30.s390x

**Comment by psychon** [comment]
> Unfortunately, I don't see this problem on other architectures. Any hint on how to debug this?

I have good news for you! Me and a debian developer already spent ages on debugging this some time ago! LGI was failing to build from source on s390x due to lots and lots of weird test failures. The result is commit a127f82af7b60fd4f76b694317eb77ff4c62bbf7 which has a commit message I recommend reading (and the other result is the insight that s390x is big endian and basically everything else is not; I don't remember which other factor made this fail only on s390x).
