### ISSUE TITLE
can't get GdkPixbuf access to work

### ISSUE THREAD

**Issue by nonchip** [pavouk/lgi#224]
I need to render a GtkImage (via GdkPixbuf) from raw rgb data, but lgi's/luajit's hand-holding logic seems to just LOVE casting things around until i can't access them anymore :/

What I tried:
```moonscript
-- the "give me your pointer" way
pixbuf = GdkPixbuf.Pixbuf.new 'RGB', false, 8, width, height
pixels = pixbuf\get_pixels!
-- type(pixels) == string, because that's what uchar*s are cast to
-- also #pixels == 0 because the first "character" in the black pixbuf is a \0 which is interpreted as the end, so i can't even do some ugly string manipulation magic to access it


-- the "i provide a giant array" way
pixels = ffi.new 'uint8_t[?]', width*height*3
pixbuf = GdkPixbuf.Pixbuf.new_from_data pixels, 'RGB', false, 8, width, height, width*3, cb_destroy, ffi.NULL
-- bad argument #2 to 'new_from_data' (table expected, got cdata)

-- trying to give it a table instead
pixels = {i,0 for i=0,(width*height*3)-1} -- tried indices 1..size too but doesn't change anything
pixbuf = GdkPixbuf.Pixbuf.new_from_data pixels, 'RGB', false, 8, width, height, width*3, cb_destroy, ffi.NULL
-- doesn't show an error message, so i try to access in a loop)
offset = (width*3*y) + (3*x)
pixels[offset]   = r
pixels[offset+1] = g
pixels[offset+2] = b
-- theoretically runs, but randomly segfaults and/or just shows random "residual" pixels instead of the all-black i clearly just filled in. also accessing like shown does set some random pixels to random values, but clearly not the ones i'm setting (not even at the right position)
```

literally every type of creating/accessing it i tried seems to fail because either lgi's marshalling or luajit's type conversions seem to want to "help" me a bit too much there, is there an actual way to do this i'm just not aware of or did i just find a bug? :/

**Comment by psychon** [comment]
I don't have much time right now, but: Did you try providing the pixel data as a string? Note that in this case one really shouldn't modify the contents of the GdkPixbuf instance, because of how Lua's strings work. `gdk_pixbuf_copy()` could be used to work around this and get a copy of the data.

Also, personally I think I'd try making `gdk_pixbuf_new_from_bytes` work. This "shifts" the problem into "how to initialise a `GBytes` instance?", but should be safer ownership-wise.

Finally: This is what I ended up with when I had to mess with image data: https://github.com/awesomeWM/awesome/blob/f03d5474cbe6cd9100e85878e1557f156dfb6d7d/lib/naughty/dbus.lua#L79-L121

**Comment by psychon** [comment]
> pixels = pixbuf\get_pixels!
> -- type(pixels) == string, because that's what uchar*s are cast to
> -- also #pixels == 0 because the first "character" in the black pixbuf is a \0 which is interpreted as the end, so i can't even do some ugly string manipulation magic to access it

Hm. That works here even when the pixels contains all zero values. Note that this actually calls https://developer.gnome.org/gdk-pixbuf/2.36/gdk-pixbuf-The-GdkPixbuf-Structure.html#gdk-pixbuf-get-pixels-with-length thanks to the `[rename-to gdk_pixbuf_get_pixels]` and this function seems to be handled correctly.

Anyway, here is some code that works for me. Can this issue be closed?
```lua
local lgi = require("lgi")
local pixbuf = lgi.GdkPixbuf
local bytes = require("bytes")

local width, height = 4, 4
local pixels = bytes.new(width * height * 3)
-- Alternatively as a string: bytes.new("abcdef")

local pb = pixbuf.Pixbuf.new_from_data(pixels, 'RGB', false, 8, width, height, width*3, function(...) print("foo", ...) end, 42)
-- Note that we have to keep 'pixels' alive as long as 'pb' exists. If 'pixels'
-- goes out of scope, it will be freed and the pixbuf will refer to "something
-- invalid". A way around this would be (but then we can no longer modify the
-- contents):
--   pb = pb:copy()

print(#pb:get_pixels())

-- This image will be black since lgi zero-initialises the buffer
print(pb:savev("/tmp/a.png", "png", {}, {}))

for i=1, width*height*3 do
    pixels[i] = 255
end

-- This image will be white since we just made it white
print(pb:savev("/tmp/b.png", "png", {}, {}))
print(#pb:get_pixels())
```

**Comment by nonchip** [comment]
thanks a lot, that works for me :)

**Comment by psychon** [comment]
To explain the `require("bytes")` above: (since it once confused me a lot)
When `lgi` is loaded, it tests `require("bytes")`. If this fails, it does `package.loaded.bytes = require("lgi.core").bytes`. Thus, if you try loading `bytes` before `lgi` (and do not have an external `bytes` package), the `require` will fail.

Perhaps it would be better to use `require("lgi.core").bytes` directly to make this more obvious? Anyway, just wanted to tell you this.

**Comment by vredesbyyrd** [comment]
@psychon 

Apologies for resurrecting a closed issue, I am just stumped on a similar issue. 

I did the following to convert raw image data to `png`, all works great.  

```lua
  width, height, rowstride, alpha, bits, channels, data = image_data:splitv(":")
  local pb = pixbuf.Pixbuf.new_from_data(dec(data), 'RGB', alpha, bits, width, height, rowstride) -- dec decodes base64
  local icon = ICON_CACHE_PATH .. "/" ..uuid().. ".png"
  pb:savev(icon, "png", {}, {})
  return icon
```
Here `image_data` looks like: `32:32:128:true:8:4:base64string...` So all the required parameters are available (width, height, rowstride, alpha, bits, channels, data)

I am now trying to convert tab "favicons" that are retrieved from a webextension. The favicons are also raw image data but are formatted like `data:image/png;base64,foobarbase64string...`

I'm lost on how to proceed when `width, height, rowstride, alpha, bits, channels` are not available. Can that information be retrieved with `GtkPixbuf` when all we have is the base64 string + image format? I admit I am a noob. Any pointers would be very appreciated.

**Comment by psychon** [comment]
> The favicons are also raw image data
> [...]
> data:image/png;

I have no clue about favicons, but are you sure this is raw pixel data? If so, why does it say `png` in there? I would guess that means this is PNG data.

Anyway, sorry, but I have no clue what that data format even is. I just thought the `png` in there was weird and might indicate that this is PNG data and not raw RGB pixel data.

**Comment by vredesbyyrd** [comment]
Your right, I'm being dumb. It's not raw pixel data, that example is `png` data. From a sample of 100 tabs, most websites serve up a `ico`: 

`data:image/x-icon;`

Followed by: 

`data:image/png;`

Lastly, a few are:

`data:image/svg+xml`

I know next to nothing about webdev stuff, it's all new to me. I'm just making a little `rofi` program that allows you to search open browser tabs, search suggestions and history. I definitely do not need to use favicons, but since the extension that I get the data from includes the icons I figured I'd try and use them. 

 What I find interesting, this [site](https://base64.guru/converter/decode/image/png) and ones like them can take only the base64 string and return a `png`.

And no reason to be sorry - I appreciate the response. I'll dig in a bit more and see if I can figure it out.

**Comment by vredesbyyrd** [comment]
Well, I way over thought this, uhg. It's as simple as decoding the base64 and saving it as a file. 

```lua
local function decode(data)
    local b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
    data = string.gsub(data, '[^'..b..'=]', '')
    return (data:gsub('.', function(x)
        if (x == '=') then return '' end
        local r,f='',(b:find(x)-1)
        for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end
        return r;
    end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x)
        if (#x ~= 8) then return '' end
        local c=0
        for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end
            return string.char(c)
    end))
end

local image_data = 'abcd'
file.write('/tmp/b.png', decode(image_data))

```
